language: java

script: mvn clean package -P strict

after_success:
  - mvn jacoco:report coveralls:report
  - bash ./deploy.sh

jdk:
  - openjdk7
  - oraclejdk8

sudo: false
cache:
  directories:
    - $HOME/.m2

env:
  global:
  - GH_REF: github.com/vbauer/houdini.git
  - secure: "ay/H2CtvrjKol8rRT6eMj7dgkjOa1t8WDMY8gTiu1iXAGoAb6DusL+Xrn8I52GbifEZqQrIM9rCwvsENv83MUyJn8hbmnSBcdEtLmrCWcZynBsRCYfmAmqyT1HoLZnxUEflVSfW7UPXLxwf6Ny4ImiNg5KLLcc/HrNeplqDyLOE="
